version: 0.2

phases:
  build:
    commands:
      - echo " Checking the date "
      - echo $date 
      - echo "Adding terraform repository"
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update -y && sudo apt-get install terraform
      - cd HelloTerraform/
      - terraform init
      - terraform validate 
      - terraform plan
      # If terraform folder from which build script will be executed contains variables.tfvar file, terraform plan command needs to include variables.tfvar This command will take all information inside variables.tfvar without requiting to provide variable names.
     #- terraform plan -var-file=variables.tfvar
      - echo Terraform execution completed on $date
