
version: 0.2

phases:
  install:
    commands:
      - echo " Checking the date "
      - echo $date 
      - echo "Adding terraform repository"
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update -y && sudo apt-get install terraform
  pre_build:
    commands:
      - pwd
      - ls -l
      - cd HelloTerraform/
      - ls -l
      - terraform init
  build:
    commands:
#       - terraform $TF_COMMAND -auto-approve
      - terraform destroy --auto-approve  

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on '$date'

